name: MechArchitech
main: net.boutopia.ToolWorx.MechArchitech.MechArchitech
version: 0.1a

commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>